<a href="https://colab.research.google.com/github/TasbihMohammed/Pandas-Practice/blob/main/tutorial-practice/Pandas_Tutorial_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Pandas:**
#### Pandas is a Python library used for data manipulation and analysis.
#### It provides DataFrames to organize, filter, and analyze structured data easily.

### **Data Structures in Pandas:**

### **1. Series:**
##### A one-dimensional labeled array that can store data of different types.

### **2. DataFrame:**
##### A two-dimensional labeled data structure with rows and columns, similar to a table in a database or a spreadsheet.

In [101]:
import pandas as pd

In [102]:
# Series:
data = [1,2,3,4,5]
index = ['a','b','c','d','e']
series = pd.Series(data,index=index)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [103]:
# Data Frame
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['c0','c1','c2'],index=['r0','r1','r2'])
print(df)

    c0  c1  c2
r0   1   2   3
r1   4   5   6
r2   7   8   9

## **Reading Files in Pandas:**

Pandas allows us to read data from different file formats and load it into a DataFrame for data analysis and manipulation.

### **Common File Formats**

- **CSV (.csv):** Stores tabular data separated by commas.
- **Excel (.xlsx):** Stores data in spreadsheets containing rows and columns.
- **JSON (.json):** Stores structured data using key-value pairs.
- **Parquet (.parquet):** A compressed, column-oriented file format that is efficient for large datasets.

### **Reading Files in Pandas**

Pandas provides different functions to read data from files,
Most of these functions return a DataFrame, allowing us to work with the data using Pandas.

In [104]:
# Uploading a Dataset
from google.colab import files

uploaded = files.upload()

Saving obesity_prediction.csv to obesity_prediction (1).csv

In [105]:
# Loading a Dataset Using Pandas
obesity_data =pd.read_csv('obesity_prediction.csv')

In [106]:
# First 5 Rows
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [107]:
# Last 10 Rows
obesity_data.tail(10)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2101,Female,25.722004,1.628470,107.218949,yes,yes,3.0,3.0,Sometimes,no,2.487070,no,0.067329,0.455823,Sometimes,Public_Transportation,Obesity_Type_III
2102,Female,25.765628,1.627839,108.107360,yes,yes,3.0,3.0,Sometimes,no,2.320068,no,0.045246,0.413106,Sometimes,Public_Transportation,Obesity_Type_III
2103,Female,21.016849,1.724268,133.033523,yes,yes,3.0,3.0,Sometimes,no,1.650612,no,1.537639,0.912457,Sometimes,Public_Transportation,Obesity_Type_III
2104,Female,21.682367,1.732383,133.043941,yes,yes,3.0,3.0,Sometimes,no,1.610768,no,1.510398,0.931455,Sometimes,Public_Transportation,Obesity_Type_III
2105,Female,21.285965,1.726920,131.335786,yes,yes,3.0,3.0,Sometimes,no,1.796267,no,1.728332,0.897924,Sometimes,Public_Transportation,Obesity_Type_III
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

### Pandas `sample()` Function

The `sample()` function randomly selects rows or columns from a DataFrame or elements from a Series.

**Note:** By default, sampling is performed without replacement, so the same row cannot be selected more than once in a single sample.

In [108]:
#  Select one random row by default.
obesity_data.sample()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2101,Female,25.722004,1.62847,107.218949,yes,yes,3.0,3.0,Sometimes,no,2.48707,no,0.067329,0.455823,Sometimes,Public_Transportation,Obesity_Type_III

In [109]:
# Select 5 random rows.
obesity_data.sample(n=5)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
496,Male,18.000000,1.720000,53.000000,yes,yes,2.000000,3.000000,Sometimes,no,2.000000,no,0.00000,2.000000,Sometimes,Public_Transportation,Insufficient_Weight
1776,Male,38.108940,1.752863,119.201465,yes,yes,2.499388,2.989791,Sometimes,no,1.959777,no,0.60810,0.646760,Sometimes,Automobile,Obesity_Type_II
1496,Male,28.421533,1.829239,107.108190,yes,yes,2.465575,2.935381,Sometimes,no,2.480555,no,1.00183,1.670313,Sometimes,Automobile,Obesity_Type_I
446,Male,19.000000,1.830000,82.000000,yes,yes,3.000000,3.000000,Frequently,no,2.000000,no,2.00000,0.000000,Sometimes,Public_Transportation,Normal_Weight
233,Female,34.000000,1.680000,77.000000,yes,no,3.000000,1.000000,Sometimes,no,2.000000,no,1.00000,0.000000,Sometimes,Automobile,Overweight_Level_II

In [110]:
# Selects 5 reproducible random rows.
obesity_data.sample(n=3,random_state=42)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
544,Female,20.406871,1.755978,53.699561,yes,yes,2.0,3.891994,Frequently,no,1.863930,no,2.870127,2.000000,no,Public_Transportation,Insufficient_Weight
1987,Female,26.000000,1.624950,111.004920,yes,yes,3.0,3.000000,Sometimes,no,2.704315,no,0.000000,0.322666,Sometimes,Public_Transportation,Obesity_Type_III
420,Male,18.000000,1.850000,60.000000,yes,yes,3.0,4.000000,Sometimes,no,2.000000,yes,2.000000,0.000000,Sometimes,Automobile,Insufficient_Weight

###**Details of DataFrames**

In [111]:
# column names as a Python list.
obesity_data.columns.tolist()

['Gender',
 'Age',
 'Height',
 'Weight',
 'family_history',
 'FAVC',
 'FCVC',
 'NCP',
 'CAEC',
 'SMOKE',
 'CH2O',
 'SCC',
 'FAF',
 'TUE',
 'CALC',
 'MTRANS',
 'Obesity']

In [112]:
# row index labels of the DataFrame.
obesity_data.index

RangeIndex(start=0, stop=2111, step=1)

In [113]:
# Number of rows , cols
obesity_data.shape

(2111, 17)

In [114]:
# Number of elements
obesity_data.size

35887

In [115]:
# Generate descriptive statistics for numerical columns.
obesity_data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [116]:
# Display a summary of the DataFrame structure and data types.
obesity_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          2111 non-null   object
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object
 5   FAVC            2111 non-null   object
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object
 9   SMOKE           2111 non-null   object
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object
 15  MTRANS          2111 non-null   object
 16  Obesity         2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

## **Accessing Data**

###**Accessing Data Using loc**

#####loc is a Pandas accessor used to select rows and columns based on their labels.
Note: loc uses labels, and the ending label in a slice is included.

In [117]:
# Selects the row with index label 0.
obesity_data.loc[0]

Gender                           Female
Age                                21.0
Height                             1.62
Weight                             64.0
family_history                      yes
FAVC                                 no
FCVC                                2.0
NCP                                 3.0
CAEC                          Sometimes
SMOKE                                no
CH2O                                2.0
SCC                                  no
FAF                                 0.0
TUE                                 1.0
CALC                                 no
MTRANS            Public_Transportation
Obesity                   Normal_Weight
Name: 0, dtype: object

In [118]:
# Selects all rows from the Age column.
obesity_data.loc[:,'Age']

0       21.000000
1       21.000000
2       23.000000
3       27.000000
4       22.000000
          ...
2106    20.976842
2107    21.982942
2108    22.524036
2109    24.361936
2110    23.664709
Name: Age, Length: 2111, dtype: float64

In [119]:
obesity_data.loc[0,'Age']

np.float64(21.0)

In [120]:
obesity_data.loc[0:10, ['Age','Height']]

     Age  Height
0   21.0    1.62
1   21.0    1.52
2   23.0    1.80
3   27.0    1.80
4   22.0    1.78
5   29.0    1.62
6   23.0    1.50
7   22.0    1.64
8   24.0    1.78
9   22.0    1.72
10  26.0    1.85

In [121]:
obesity_data.loc[[0,7,10],['Age','Height','Weight']]

     Age  Height  Weight
0   21.0    1.62    64.0
7   22.0    1.64    53.0
10  26.0    1.85   105.0

In [122]:
obesity_data.loc[8:20,'Age':'FAF']

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF
8,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0
9,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0
10,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0
11,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,no,2.0,yes,2.0
12,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,no,3.0,no,2.0
13,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0
14,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,no,1.0,no,1.0
15,22.0,1.70,66.0,yes,no,3.0,3.0,Always,no,2.0,yes,2.0
16,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,no,1.0,no,1.0
17,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,no,2.0,no,0.0
18,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0
19,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,0.0
20,22.0,1.65,80.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,3.0

### **Accessing Data Using `iloc`**

`iloc` is a Pandas accessor used to select rows and columns based on their integer positions, rather than their index labels.

It allows us to access specific rows, columns, or individual values using zero-based indexing.

**Note:** `iloc` uses zero-based integer positions, and the ending position in a slice is excluded.

In [123]:
obesity_data.iloc[0:11 , 0]

0     Female
1     Female
2       Male
3       Male
4       Male
5       Male
6     Female
7       Male
8       Male
9       Male
10      Male
Name: Gender, dtype: object

In [124]:
obesity_data.iloc[[10,20,30],[0,1,2]]

   Gender   Age  Height
10   Male  26.0    1.85
20   Male  22.0    1.65
30   Male  29.0    1.77

### **Accessing Single Values Using `at` and `iat`**

- **`at`**: Accesses a single value using row and column labels.
- **`iat`**: Accesses a single value using integer positions.


**Difference from `loc` and `iloc`:** `loc` and `iloc` support selecting multiple rows and columns, while `at` and `iat` are designed for accessing a single value efficiently.

In [125]:
obesity_data.at[0,'Age']

np.float64(21.0)

In [126]:
obesity_data.iat[0,2]

np.float64(1.62)

### **Accessing Columns: Shorthand and Dot Notation**

 Both methods can access a single column, returning a Series.

**Note:** Square bracket notation is more flexible and is recommended when column names contain spaces, special characters, or conflict with existing DataFrame attributes.

In [127]:
# Shorthand
obesity_data[['Age','Gender']]

            Age  Gender
0     21.000000  Female
1     21.000000  Female
2     23.000000    Male
3     27.000000    Male
4     22.000000    Male
...         ...     ...
2106  20.976842  Female
2107  21.982942  Female
2108  22.524036  Female
2109  24.361936  Female
2110  23.664709  Female

[2111 rows x 2 columns]

In [128]:
# Dot Notation
obesity_data.Height

0       1.620000
1       1.520000
2       1.800000
3       1.800000
4       1.780000
          ...
2106    1.710730
2107    1.748584
2108    1.752206
2109    1.739450
2110    1.738836
Name: Height, Length: 2111, dtype: float64

### **Filtering Data based on conditions**

### **Filtering Data Using `loc`**

The `loc` accessor can be used to filter rows based on conditions and select specific columns at the same time.

**Syntax:**

`df.loc[condition, columns]`

- `condition`: The condition used to filter rows.
- `columns`: The columns to select. Use `:` to select all columns.

**Note:** Using `loc` allows us to filter rows and select columns in a single operation.

In [129]:
obesity_data.loc[(obesity_data['Age']>18)&(obesity_data['Height']>1.7),['Gender','Age']].head(10)

    Gender   Age
2     Male  23.0
3     Male  27.0
4     Male  22.0
8     Male  24.0
9     Male  22.0
10    Male  26.0
11  Female  21.0
13    Male  41.0
14    Male  23.0
16    Male  27.0

### **Regular Expressions (Regex)**

In [130]:
obesity_data[obesity_data['Obesity'].str.startswith('Normal')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,Male,25.0,1.66,68.0,no,yes,2.0,3.0,Sometimes,yes,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
493,Male,20.0,1.80,65.0,no,yes,2.0,3.0,Frequently,no,1.0,no,2.0,0.0,Sometimes,Motorbike,Normal_Weight
494,Female,18.0,1.67,66.0,no,yes,3.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
495,Male,19.0,1.80,60.0,yes,yes,3.0,1.0,Always,no,1.0,yes,0.0,0.0,no,Motorbike,Normal_Weight
497,Male,20.0,1.56,45.0,no,no,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

### **Updating Data Using `loc`**

In [131]:
obesity_data.loc[0,'Age'] = 22
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,22.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [132]:
obesity_data.loc[:,'SMOKE']='yes'
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,22.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [133]:
obesity_data.loc[[2,3],'Height']=1.6
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,22.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

### **`iloc`,`at`,`iat` for Updating Data**

In [134]:
obesity_data.iloc[:,9]='doesnt matter'
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,22.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,doesnt matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesnt matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [135]:
obesity_data.at[2,'Obesity']='Overrr'
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,22.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,doesnt matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrr
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesnt matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [136]:
obesity_data.iat[2,4]='secret'
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,22.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,doesnt matter,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.60,77.0,secret,no,2.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrr
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,doesnt matter,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,doesnt matter,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [137]:
# shorthand
obesity_data['SMOKE']='No'
obesity_data.tail()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,No,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,No,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,No,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,No,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,No,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

### **Transforming Data Using `apply()`**

The `apply()` method in Pandas is used to apply a function to a Series or along the rows or columns of a DataFrame.

It is useful for performing custom transformations on data, such as modifying values, applying calculations, or creating new values based on specific conditions.

**Key Points:**
- `apply()` can work with both built-in and user-defined functions.
- It can be used with `lambda` functions for simple operations.
- `axis=0`: Applies the function to each column.
- `axis=1`: Applies the function to each row.

In [138]:
obesity_data['Age']=obesity_data['Age'].apply(lambda x:x+5)
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,27.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,No,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,26.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,No,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,28.0,1.60,77.0,secret,no,2.0,3.0,Sometimes,No,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrr
3,Male,32.0,1.60,87.0,no,no,3.0,3.0,Sometimes,No,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,27.0,1.78,89.8,no,no,2.0,1.0,Sometimes,No,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [139]:
obesity_data['Age Category']=obesity_data['Age'].apply(lambda x: 'very young' if x<25 else 'not so young')
obesity_data.head(10)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,27.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,No,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,not so young
1,Female,26.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,No,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,not so young
2,Male,28.0,1.60,77.0,secret,no,2.0,3.0,Sometimes,No,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrr,not so young
3,Male,32.0,1.60,87.0,no,no,3.0,3.0,Sometimes,No,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,not so young
4,Male,27.0,1.78,89.8,no,no,2.0,1.0,Sometimes,No,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,not so young
5,Male,34.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,No,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,not so young
6,Female,28.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,No,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,not so young
7,Male,27.0,1.64,53.0,no,no,2.0,3.0,Sometimes,No,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,not so young
8,Male,29.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,No,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight,not so young
9,Male,27.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,No,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight,not so young

In [140]:
import numpy as np

obesity_data['New Age Category']= np.where(obesity_data.Age < 25,'young','not young')
obesity_data.tail(10)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
2101,Female,30.722004,1.628470,107.218949,yes,yes,3.0,3.0,Sometimes,No,2.487070,no,0.067329,0.455823,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2102,Female,30.765628,1.627839,108.107360,yes,yes,3.0,3.0,Sometimes,No,2.320068,no,0.045246,0.413106,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2103,Female,26.016849,1.724268,133.033523,yes,yes,3.0,3.0,Sometimes,No,1.650612,no,1.537639,0.912457,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2104,Female,26.682367,1.732383,133.043941,yes,yes,3.0,3.0,Sometimes,No,1.610768,no,1.510398,0.931455,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2105,Female,26.285965,1.726920,131.335786,yes,yes,3.0,3.0,Sometimes,No,1.796267,no,1.728332,0.897924,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2106,Female,25.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,No,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2107,Female,26.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,No,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2108,Female,27.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,No,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2109,Female,29.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,No,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2110,Female,28.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,No,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young

### **Inserting and Dropping Columns in Pandas**
**1. Inserting Columns**

The `insert()` method allows us to add a new column at a specific position in a DataFrame.

**2. Dropping Columns**

The `drop()` method is used to remove one or more columns from a DataFrame.

**Note:** By default, `drop()` returns a new DataFrame without modifying the original one. Use `inplace=True` to modify the original DataFrame directly.

In [141]:
obesity_data.insert(2,'BMI',20)
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,27.0,20,1.62,64.0,yes,no,2.0,3.0,Sometimes,No,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,not so young,not young
1,Female,26.0,20,1.52,56.0,yes,no,3.0,3.0,Sometimes,No,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,not so young,not young
2,Male,28.0,20,1.60,77.0,secret,no,2.0,3.0,Sometimes,No,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrr,not so young,not young
3,Male,32.0,20,1.60,87.0,no,no,3.0,3.0,Sometimes,No,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,not so young,not young
4,Male,27.0,20,1.78,89.8,no,no,2.0,1.0,Sometimes,No,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,not so young,not young

In [142]:
obesity_data.drop(columns='BMI',inplace=True)
obesity_data.tail()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
2106,Female,25.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,No,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2107,Female,26.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,No,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2108,Female,27.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,No,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2109,Female,29.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,No,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young
2110,Female,28.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,No,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,not so young,not young

In [143]:
obesity_data.insert(2,'BMI',(obesity_data['Weight'] / obesity_data['Height']**2))
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,27.0,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,No,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,not so young,not young
1,Female,26.0,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,No,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,not so young,not young
2,Male,28.0,30.078125,1.60,77.0,secret,no,2.0,3.0,Sometimes,No,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrr,not so young,not young
3,Male,32.0,33.984375,1.60,87.0,no,no,3.0,3.0,Sometimes,No,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,not so young,not young
4,Male,27.0,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,No,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,not so young,not young

### **Deleting and Renaming Columns in Pandas**

**1. Deleting Columns**

The `del` statement can be used to delete a column directly from the original DataFrame.


Another way to delete columns is by using the `pop()` method, which removes a column and returns its values as a Series.

**2. Renaming Columns**

The `rename()` method is used to change column names in a DataFrame.

**Syntax:**
```python
df.rename(columns={'old_name': 'new_name'})
```

**Key Points:**
- `del` deletes a column directly from the original DataFrame.
- `pop()` removes a column and returns it as a Series.
- `rename()` returns a new DataFrame by default.
- `inplace=True` modifies the original DataFrame directly when using `rename()`.

In [144]:
# del
del obesity_data['CAEC']
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category,New Age Category
0,Female,27.0,24.386526,1.62,64.0,yes,no,2.0,3.0,No,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,not so young,not young
1,Female,26.0,24.238227,1.52,56.0,yes,no,3.0,3.0,No,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,not so young,not young
2,Male,28.0,30.078125,1.60,77.0,secret,no,2.0,3.0,No,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrr,not so young,not young
3,Male,32.0,33.984375,1.60,87.0,no,no,3.0,3.0,No,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,not so young,not young
4,Male,27.0,28.342381,1.78,89.8,no,no,2.0,1.0,No,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,not so young,not young

In [145]:
# pop
# This removes the BMI column from df
# and stores its values in the bmi variable.
bmi = obesity_data.pop('BMI')
print(bmi)

0       24.386526
1       24.238227
2       30.078125
3       33.984375
4       28.342381
          ...
2106    44.901475
2107    43.741923
2108    43.543817
2109    44.071535
2110    44.144338
Name: BMI, Length: 2111, dtype: float64

In [146]:
# rename
obesity_data.rename(columns={'Obesity':'Obesity_Category','SMOKE':'Smoke'},inplace=True)
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,Smoke,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity_Category,Age Category,New Age Category
0,Female,27.0,1.62,64.0,yes,no,2.0,3.0,No,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,not so young,not young
1,Female,26.0,1.52,56.0,yes,no,3.0,3.0,No,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,not so young,not young
2,Male,28.0,1.60,77.0,secret,no,2.0,3.0,No,2.0,no,2.0,1.0,Frequently,Public_Transportation,Overrr,not so young,not young
3,Male,32.0,1.60,87.0,no,no,3.0,3.0,No,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,not so young,not young
4,Male,27.0,1.78,89.8,no,no,2.0,1.0,No,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,not so young,not young

### **Merging DataFrames in Pandas**

Merging is the process of combining two DataFrames based on a common column or key.

It is useful when related information is stored in separate DataFrames and we want to combine it into a single DataFrame.

In this example, we will merge two DataFrames using the `Student_ID` column.

In [147]:
import pandas as pd

# Create the first DataFrame containing student names
students = pd.DataFrame({
    'Student_ID': [1, 2, 3, 4],
    'Name': ['Ali', 'Sara', 'Omar', 'Mona']
})

# Create the second DataFrame containing student grades
grades = pd.DataFrame({
    'Student_ID': [2, 3, 4, 5],
    'Grade': [85, 90, 78, 95]
})

# Display the first DataFrame
print("Students DataFrame:")
print(students)

# Display the second DataFrame
print("\nGrades DataFrame:")
print(grades)

Students DataFrame:
   Student_ID  Name
0           1   Ali
1           2  Sara
2           3  Omar
3           4  Mona

Grades DataFrame:
   Student_ID  Grade
0           2     85
1           3     90
2           4     78
3           5     95

### **Inner Merge**

An inner merge returns only the rows that have matching keys in both DataFrames.

Rows that do not have a matching key in the other DataFrame are excluded from the result.

This is the default merge type in Pandas.

In [148]:
# Merge the two DataFrames using the common Student_ID column
# Keep only students whose IDs exist in both DataFrames
inner_merged = pd.merge(
    students,
    grades,
    on='Student_ID',
    how='inner'
)

# Display the merged DataFrame
print(inner_merged)

   Student_ID  Name  Grade
0           2  Sara     85
1           3  Omar     90
2           4  Mona     78

### **Outer Merge**

An outer merge returns all rows from both DataFrames.

If a key exists in one DataFrame but has no matching key in the other DataFrame, the missing values are filled with `NaN`.

This is useful when we want to preserve all records from both DataFrames.

In [149]:
outer_merged=pd.merge(students,grades,how='outer',on='Student_ID')
print(outer_merged)

   Student_ID  Name  Grade
0           1   Ali    NaN
1           2  Sara   85.0
2           3  Omar   90.0
3           4  Mona   78.0
4           5   NaN   95.0

### **Left Merge**

A left merge keeps all rows from the left DataFrame (the first DataFrame).

Matching data from the right DataFrame is added to the result. If there is no matching key, the corresponding values from the right DataFrame are filled with `NaN`.

In [150]:
left_merged= pd.merge(students,grades,how='left',on='Student_ID')
print(left_merged)

   Student_ID  Name  Grade
0           1   Ali    NaN
1           2  Sara   85.0
2           3  Omar   90.0
3           4  Mona   78.0

### **Right Merge**

A right merge keeps all rows from the right DataFrame (the second DataFrame).

Matching data from the left DataFrame is added to the result. If there is no matching key, the corresponding values from the left DataFrame are filled with `NaN`.

In [151]:
right_merged=pd.merge(students,grades,how='right',on='Student_ID')
print(right_merged)

   Student_ID  Name  Grade
0           2  Sara     85
1           3  Omar     90
2           4  Mona     78
3           5   NaN     95

### **Merging DataFrames Using Different Column Names**

Sometimes, the columns used to match records have different names in the two DataFrames.

In this case, we can use `left_on` to specify the column name in the left DataFrame and `right_on` to specify the column name in the right DataFrame.

Unlike `on`, which is used when both DataFrames share the same column name, `left_on` and `right_on` allow us to merge DataFrames using differently named columns.

In [152]:
import pandas as pd

# Create the first DataFrame
students = pd.DataFrame({
    'Student_ID': [1, 2, 3, 4],
    'Name': ['Ali', 'Sara', 'Omar', 'Mona']
})

# Create the second DataFrame
grades = pd.DataFrame({
    'ID': [2, 3, 4, 5],
    'Grade': [85, 90, 78, 95]
})

# Merge using columns with different names
merged_data = pd.merge(
    students,
    grades,
    left_on='Student_ID',  # Key column in the left DataFrame
    right_on='ID',         # Key column in the right DataFrame
    how='inner'            # Keep matching records only
)

# Remove the extra ID column after merging
merged_data = merged_data.drop(columns=['ID'])

# Display the cleaned DataFrame
print(merged_data)

   Student_ID  Name  Grade
0           2  Sara     85
1           3  Omar     90
2           4  Mona     78

### **Summary: Concatenation in Pandas**

The `pd.concat()` function combines two or more DataFrames along a specified axis.

- `axis=0`: Adds rows vertically.
- `axis=1`: Adds columns horizontally and aligns rows by their index labels.
- `ignore_index=True`: Creates a new sequential index for the concatenation result.
- `NaN` appears when data is missing after alignment.

**Difference between `concat()` and `merge()`:**

Use `concat()` mainly to stack datasets or place them side by side. Use `merge()` to combine related data based on matching key columns.

In [153]:
import pandas as pd

# Create the first DataFrame
students_1 = pd.DataFrame({
    'Name': ['Ali', 'Sara'],
    'Grade': [85, 90]
})

# Create the second DataFrame
students_2 = pd.DataFrame({
    'Name': ['Omar', 'Mona'],
    'Grade': [78, 95]
})

# Display the first DataFrame
print("Students 1:")
print(students_1)

# Display the second DataFrame
print("\nStudents 2:")
print(students_2)

Students 1:
   Name  Grade
0   Ali     85
1  Sara     90

Students 2:
   Name  Grade
0  Omar     78
1  Mona     95

In [154]:
all_students= pd.concat([students_1,students_2],axis=0,ignore_index=True)
print(all_students)

   Name  Grade
0   Ali     85
1  Sara     90
2  Omar     78
3  Mona     95

### **Detecting Null Values**

Missing values are values that are absent from a dataset.

Pandas provides several methods to detect missing values, such as `isnull()` and `notnull()`.

- `isnull()` returns `True` for missing values and `False` otherwise.
- `notnull()` returns `True` for non-missing values and `False` for missing values.

These methods help us identify missing data before performing analysis.

In [155]:
import pandas as pd
import numpy as np

# Create a DataFrame containing some missing values
students = pd.DataFrame({
    'Name': ['Ali', 'Sara', 'Omar', 'Mona','Yara'],
    'Age': [19, np.nan, 20, np.nan ,22],
    'Grade': [85, 90, np.nan, 95,np.nan]
})

# Display the DataFrame
print(students)

   Name   Age  Grade
0   Ali  19.0   85.0
1  Sara   NaN   90.0
2  Omar  20.0    NaN
3  Mona   NaN   95.0
4  Yara  22.0    NaN

In [156]:
print(students.isnull())

    Name    Age  Grade
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False
4  False  False   True

In [157]:
print(students.notnull().sum())

Name     5
Age      3
Grade    3
dtype: int64

In [158]:
# Count all missing values in the entire DataFrame
print(students.isnull().sum().sum())

4

### **Handling Null Values**

After detecting missing values, we need to decide how to handle them.

Pandas provides methods such as `dropna()` to remove missing data and `fillna()` to replace missing values.

The appropriate method depends on the dataset and the purpose of the analysis. Removing data may cause information loss, while filling missing values requires choosing a suitable replacement.

### Removing Missing Values with `dropna()`

The `dropna()` method removes rows containing missing values by default.

It is useful when rows with incomplete data should not be included in the analysis.

By default, `dropna()` returns a new DataFrame and does not modify the original DataFrame in place.

In [159]:
clean_students = students.dropna()
print(clean_students)

  Name   Age  Grade
0  Ali  19.0   85.0

In [160]:
clean_columns = students.dropna(axis=1)
print(clean_columns)

   Name
0   Ali
1  Sara
2  Omar
3  Mona
4  Yara

### **Filling Missing Values with `fillna()`**

The `fillna()` method replaces missing values with specified values.

It can be used to fill missing values with a constant, such as `0` or `"Unknown"`, or with calculated values, such as the mean or median of a column.

The replacement strategy should be selected based on the meaning of the data.

In [161]:
# Replace all missing values with 0
filled_students = students.fillna(0)
print(filled_students)

   Name   Age  Grade
0   Ali  19.0   85.0
1  Sara   0.0   90.0
2  Omar  20.0    0.0
3  Mona   0.0   95.0
4  Yara  22.0    0.0

In [162]:
mean_grade = students['Grade'].fillna(students['Grade'].mean())
median_age = students['Age'].fillna(students['Age'].interpolate())
students.fillna({'Grade':mean_grade,'Age':median_age},inplace=True)
print(students)

   Name   Age  Grade
0   Ali  19.0   85.0
1  Sara  19.5   90.0
2  Omar  20.0   90.0
3  Mona  21.0   95.0
4  Yara  22.0   90.0

In [163]:
#The interpolate() method in Pandas:
# is used to estimate missing values based on
# existing values in a dataset.

#By default, it uses linear interpolation,
# which estimates missing values
# by assuming a linear relationship between the available values.

#It is useful when the values follow a sequence,
# such as time series data or measurements collected over time.

temperature = pd.Series([10, 20, np.nan, 40, 50])
temperature.fillna(temperature.interpolate(),inplace=True)
print(temperature)

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
dtype: float64

### **Grouping Data with `groupby()`**

The `groupby()` method in Pandas is used to group rows based on one or more columns.

After grouping the data, we can apply aggregate functions such as `sum()`, `mean()`, `count()`, `min()`, and `max()` to summarize each group.

The grouping process follows three steps:

1. **Split:** Divide the data into groups based on a column or columns.
2. **Apply:** Apply a function to each group.
3. **Combine:** Combine the results into a summarized output.

In [164]:
obesity_data.groupby('Gender').count()

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,Smoke,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity_Category,Age Category,New Age Category
Gender,,,,,,,,,,,,,,,,,
Female,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043
Male,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068

In [166]:
obesity_data.groupby('Gender')['Height'].mean()

Gender
Female    1.643298
Male      1.758316
Name: Height, dtype: float64

In [168]:
obesity_data.groupby('Gender')['Weight'].aggregate(['mean','median','std'])

             mean    median        std
Gender
Female  82.302364  78.00000  29.723904
Male    90.769478  89.94547  21.407030